services:
  web:
    container_name: albisleasingapp # TODO: chang me for new instance
    build: .
    #    image: "traefik/whoami"
    environment:
      SHOPIFY_APP_URL: "https://albisleasingapp.cpro-server.de"
      SHOPIFY_SHOP: "helge-test.myshopify.com"
      HOST: "0.0.0.0"
      SHOPIFY_API_KEY: "809a6d540ff4edfbd302c10e2895d03a"
      SHOPIFY_API_SECRET: "5c41e11efc7d7e340ac54ea9403c6f66"
      SCOPES: "write_products,write_orders,read_orders"
      DATABASE_URL: "mysql://root:1WrPZqlCnk4CHbpd31cq@albisleasingapp_db:3306/albisleasingapp" # TODO: change me for new instance
    labels:
      - traefik.enable=true
      - traefik.http.routers.albisleasingapp.rule=Host(`albisleasingapp.cpro-server.de`) # TODO: change me for new instance
      - traefik.http.routers.albisleasingapp.entrypoints=websecure
      - traefik.http.routers.albisleasingapp.tls.certresolver=letsencrypt
    #   - traefik.http.services.ebike.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - web
      - intern
  # might be needed, but seems to work without
  #    dns:
  #      - 8.8.8.8
  db:
    container_name: albisleasingapp_db # TODO: change me for new instance
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ../databaseData/albisleasingapp:/var/lib/mysql # TODO: change me for new instnaces
    environment:
      - MARIADB_INITDB_SKIP_TZINFO=true
        #  - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=1WrPZqlCnk4CHbpd31cq # TODO: you may change me
    networks:
      - intern

networks:
  web:
    external: true
  intern:
    external: false
