# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d26fcc8d70e2ee344e86b88ff3ea8a89"
name = "albis"
application_url = "https://frame-edges-wonder-dairy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "commerce-albis-leasing.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://frame-edges-wonder-dairy.trycloudflare.com/auth/callback",
  "https://frame-edges-wonder-dairy.trycloudflare.com/auth/shopify/callback",
  "https://frame-edges-wonder-dairy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
